version: '3.8'

services:
  mongodb:
    image: docker.io/library/mongo:7.0
    container_name: gamified-learning-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: gamified-learning
    networks:
      - gamified-learning-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gamified-learning-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/gamified-learning
      JWT_SECRET: ${JWT_SECRET:-change-this-secret-in-production}
      JWT_EXPIRE: 7d
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - gamified-learning-network
    volumes:
      # Mount source code for development (comment out for production)
      - ./:/app
      - /app/node_modules

networks:
  gamified-learning-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
